version: '3.4'

services:
  example-service:
    image: example-service:staging-20201106-da42a073ad
    build:
      context: .
      args:
        - 'APP_BASE_HREF=/'
        - 'APP_DEPLOY_URL=/'
        - 'APP_NPM_BUILD_COMMANDS=build:docker'
        - 'APP_BUILD_CONFIGURATION=staging-docker'
        - 'APP_NPM_BUILD_COMMAND_DELIMITER=,'
        - 'APP_REPO=example-service'
    ports:
      - 5000
