version: '3.4'

services:
  example-service:
    image: example-service:staging-20201112-21f318b47e
    build:
      context: .
      args:
        - 'APP_NPM_BUILD_COMMANDS=build:docker:staging'
        - 'APP_NPM_BUILD_COMMAND_DELIMITER=,'
    ports:
      - 5000
