version: '3.4'

services:
  example-service:
    image: example-service:staging-20201112-7df77a216c
    build:
      context: .
      args:
        - 'APP_NPM_BUILD_COMMANDS=build:docker:staging'
        - 'APP_NPM_BUILD_COMMAND_DELIMITER=@@DIB_APP_NPM_BUILD_COMMAND_DELIMITER@@'
        - 'APP_REPO='
    ports:
      - 5000
      - 5001
