version: "3.4"

services:
  {{DIB_APP_IMAGE}}:
    labels:
      kompose.image-pull-secret: "{{DIB_KOMPOSE_IMAGE_PULL_SECRET}}"
      kompose.image-pull-policy: "{{DIB_KOMPOSE_IMAGE_PULL_POLICY}}"
      kompose.service.type: "{{DIB_KOMPOSE_SERVICE_TYPE}}"
      kompose.service.expose: "{{DIB_KOMPOSE_SERVICE_EXPOSE}}"
      kompose.service.expose.tls-secret: "{{DIB_KOMPOSE_SERVICE_EXPOSE_TLS_SECRET}}"
      kompose.service.nodeport.port: "{{DIB_KOMPOSE_SERVICE_NODEPORT_PORT}}"
    image: {{DIB_APPS_CONTAINER_REGISTRY}}/{{DIB_APP_PROJECT}}/{{DIB_APP_IMAGE}}:{{DIB_APP_IMAGE_TAG}}
    container_name: {{DIB_APP_IMAGE}}
    hostname: {{DIB_APP_IMAGE}}
    ports:
      - {{DIB_APP_PORT}}:{{DIB_APP_PORT}}
    env_file:
      - ./{{DIB_APP_PROJECT}}-{{DIB_APP_FRAMEWORK}}-project.env
      - ./{{DIB_APP_PROJECT}}-{{DIB_APP_FRAMEWORK}}-{{DIB_APP_ENVIRONMENT}}-common.env
      - ./{{DIB_APP_IMAGE}}-service.env
      - ./{{DIB_APP_IMAGE}}-app.env
    network_mode: {{DIB_DOCKER_COMPOSE_NETWORK_MODE}}
    deploy:
      replicas: {{DIB_DOCKER_COMPOSE_DEPLOY_REPLICAS}}
#    healthcheck:
#      test: ["CMD", "/scripts/healthcheck.sh", "{{DIB_APP_IMAGE}}", "{{DIB_KOMPOSE_SERVICE_NODEPORT_PORT}}", "/api/health"]
#      start_period: {{DIB_DOCKER_COMPOSE_HEALTHCHECK_START_PERIOD}}
#      interval: {{DIB_DOCKER_COMPOSE_HEALTHCHECK_INTERVAL}}
#      timeout: {{DIB_DOCKER_COMPOSE_HEALTHCHECK_TIMEOUT}}
#      retries: {{DIB_DOCKER_COMPOSE_HEALTHCHECK_RETRIES}}